var annotated_dup =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "C4_Board", "class_c4___board.html", "class_c4___board" ],
    [ "C4_UI", "class_c4___u_i.html", "class_c4___u_i" ],
    [ "Diamond_XO_Board", "class_diamond___x_o___board.html", "class_diamond___x_o___board" ],
    [ "Diamond_XO_UI", "class_diamond___x_o___u_i.html", "class_diamond___x_o___u_i" ],
    [ "GameAI", "class_game_a_i.html", null ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "Infinity_TTT_Board", "class_infinity___t_t_t___board.html", "class_infinity___t_t_t___board" ],
    [ "Infinity_TTT_UI", "class_infinity___t_t_t___u_i.html", "class_infinity___t_t_t___u_i" ],
    [ "InfinityMoveInfo", "struct_infinity_move_info.html", "struct_infinity_move_info" ],
    [ "Memory_XO_Board", "class_memory___x_o___board.html", "class_memory___x_o___board" ],
    [ "Memory_XO_UI", "class_memory___x_o___u_i.html", "class_memory___x_o___u_i" ],
    [ "Misere_TTT_Board", "class_misere___t_t_t___board.html", "class_misere___t_t_t___board" ],
    [ "Misere_TTT_UI", "class_misere___t_t_t___u_i.html", "class_misere___t_t_t___u_i" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "Numerical_TTT_Board", "class_numerical___t_t_t___board.html", "class_numerical___t_t_t___board" ],
    [ "Numerical_TTT_UI", "class_numerical___t_t_t___u_i.html", "class_numerical___t_t_t___u_i" ],
    [ "Obstacles_TTT_Board", "class_obstacles___t_t_t___board.html", "class_obstacles___t_t_t___board" ],
    [ "Obstacles_TTT_UI", "class_obstacles___t_t_t___u_i.html", "class_obstacles___t_t_t___u_i" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Point", "struct_point.html", "struct_point" ],
    [ "Pyramid_X_O_Board", "class_pyramid___x___o___board.html", "class_pyramid___x___o___board" ],
    [ "Pyramid_XO_UI", "class_pyramid___x_o___u_i.html", "class_pyramid___x_o___u_i" ],
    [ "sus_board", "classsus__board.html", "classsus__board" ],
    [ "sus_ui", "classsus__ui.html", "classsus__ui" ],
    [ "TTT_Board", "class_t_t_t___board.html", "class_t_t_t___board" ],
    [ "TTT_UI", "class_t_t_t___u_i.html", "class_t_t_t___u_i" ],
    [ "UI", "class_u_i.html", "class_u_i" ],
    [ "Word_TTT_Board", "class_word___t_t_t___board.html", "class_word___t_t_t___board" ],
    [ "Word_TTT_UI", "class_word___t_t_t___u_i.html", "class_word___t_t_t___u_i" ],
    [ "XO_4_x_4_Board", "class_x_o__4__x__4___board.html", "class_x_o__4__x__4___board" ],
    [ "XO_4_x_4_UI", "class_x_o__4__x__4___u_i.html", "class_x_o__4__x__4___u_i" ],
    [ "XO_5x5_Board", "class_x_o__5x5___board.html", "class_x_o__5x5___board" ],
    [ "XO_5x5_UI", "class_x_o__5x5___u_i.html", "class_x_o__5x5___u_i" ]
];